# Generated by Django 4.1.5 on 2023-04-04 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('address', models.CharField(max_length=150, verbose_name='Address')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='State')),
                ('town_city', models.CharField(blank=True, max_length=50, null=True, verbose_name='City')),
                ('street', models.CharField(max_length=50, verbose_name='Street')),
                ('postcode', models.PositiveIntegerField(verbose_name='Postcode')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated on')),
                ('address_type', models.CharField(choices=[('NN', 'None'), ('SA', 'Shipping Address'), ('BA', 'Billing Address')], default='NN', max_length=2, verbose_name='Address Type')),
                ('default', models.BooleanField(default=False, verbose_name='Set as Default ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'ordering': ['-updated_on'],
            },
        ),
    ]
