# Generated by Django 4.1.5 on 2023-03-08 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='core/portfolio/ccategory_img')),
                ('alt_text', models.CharField(default='image', help_text='enter an alternate text for this image', max_length=50)),
                ('published', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('update_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PortfolioCat',
                'verbose_name_plural': 'PortfolioCats',
                'ordering': ('-created_on',),
            },
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='alt_text',
            field=models.CharField(default='', help_text='enter an alternate text for this image', max_length=50),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='category',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.portfoliocat'),
        ),
    ]
