# Generated by Django 4.1.5 on 2023-03-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_portfoliocat_alter_portfolio_alt_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='update_on',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='update_on',
        ),
        migrations.RemoveField(
            model_name='gallary',
            name='update_on',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='update_on',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='update_on',
        ),
        migrations.RemoveField(
            model_name='portfoliocat',
            name='update_on',
        ),
        migrations.RemoveField(
            model_name='position',
            name='update_on',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='update_on',
        ),
        migrations.RemoveField(
            model_name='review',
            name='update_on',
        ),
        migrations.RemoveField(
            model_name='service',
            name='update_on',
        ),
        migrations.AddField(
            model_name='event',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gallary',
            name='caption',
            field=models.CharField(default='', help_text='give a name for this image', max_length=50),
        ),
        migrations.AddField(
            model_name='gallary',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='portfoliocat',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='portfoliocat',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='position',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='review',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='service',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='gallary',
            name='alt_text',
            field=models.CharField(blank=True, default='', help_text='enter an alternate text for this image', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='alt_text',
            field=models.CharField(blank=True, help_text='enter an alternate text for this image', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliocat',
            name='alt_text',
            field=models.CharField(blank=True, default='', help_text='enter an alternate text for this image', max_length=50, null=True),
        ),
    ]
