# Generated by Django 4.1.5 on 2023-03-11 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_event_update_on_remove_faq_update_on_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'ordering': ('-subscribed_on',), 'verbose_name': 'subscriber', 'verbose_name_plural': 'subscribers'},
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='subcribed_on',
        ),
        migrations.AddField(
            model_name='contact',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='subscribed_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
