# Generated by Django 4.1.5 on 2023-03-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contact_phone_alter_event_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='', upload_to='core/event'),
        ),
        migrations.AlterField(
            model_name='portfoliocat',
            name='image',
            field=models.ImageField(upload_to='core/portfolio/category_img'),
        ),
    ]
