# Generated by Django 4.1.5 on 2023-04-05 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_orderproduct_product_delete_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(default='')),
                ('image', models.ImageField(upload_to='core/event/category_img')),
                ('alt_text', models.CharField(blank=True, default='', help_text='enter an alternate text for this image', max_length=50, null=True)),
                ('published', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'EventCat',
                'verbose_name_plural': 'EventCats',
                'ordering': ('-created_on',),
            },
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.eventcat'),
        ),
    ]
