# Generated by Django 4.1.5 on 2023-02-11 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_content1_alter_article_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
