# Generated by Django 4.1.5 on 2023-03-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_block_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='short_description',
            field=models.CharField(default='', help_text='give a short description in not more than 225 words. this will help users find your post on search engines', max_length=225),
        ),
    ]
