# Generated by Django 4.1.5 on 2023-02-11 03:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content1',
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(default='', help_text='use this field as video description when providing video url'),
        ),
    ]
