# Generated by Django 4.1.5 on 2023-03-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_is_event_article_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Please add alternate text. this text gets displayed when the image fails to load on time', max_length=50, null=True, verbose_name='alt text'),
        ),
        migrations.AlterField(
            model_name='article',
            name='short_description',
            field=models.CharField(default='', help_text='give a short description in not more than 160 chars. this will help users find your post on search engines', max_length=160),
        ),
    ]
