# Generated by Django 4.1.5 on 2023-04-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_viewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
